"""initial_schema_users_projects_tasks

Revision ID: cacb644cae29
Revises: e88c0b20c4b2
Create Date: 2026-05-10 23:20:36.675965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cacb644cae29'
down_revision: Union[str, None] = 'e88c0b20c4b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('id', sa.Uuid(), nullable=False))
    op.add_column('project_members', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('project_members', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_project_members_id'), 'project_members', ['id'], unique=False)
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_unique_constraint('uq_project_member', 'project_members', ['project_id', 'user_id'])
    op.drop_column('project_members', 'joined_at')
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('projects', 'slug',
               existing_type=sa.VARCHAR(length=220),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'ARCHIVED', name='project_status_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index('ix_projects_owner_status', table_name='projects')
    op.drop_index('ix_projects_status', table_name='projects')
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=False)
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('BACKLOG', 'TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'CANCELLED', name='task_status_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='task_priority_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('tasks', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               type_=postgresql.ARRAY(sa.String(length=100)),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_reporter_id'), 'tasks', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MEMBER', 'VIEWER', name='user_role_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index('ix_users_email_active', table_name='users', postgresql_where='(is_active = true)')
    op.drop_index('ix_users_role', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_email_active', 'users', ['email'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('ADMIN', 'MEMBER', 'VIEWER', name='user_role_enum'),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_reporter_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.alter_column('tasks', 'tags',
               existing_type=postgresql.ARRAY(sa.String(length=100)),
               type_=postgresql.ARRAY(sa.VARCHAR(length=50)),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('tasks', 'priority',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='task_priority_enum'),
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('BACKLOG', 'TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'CANCELLED', name='task_status_enum'),
               existing_nullable=False)
    op.alter_column('tasks', 'title',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_index('ix_projects_owner_status', 'projects', ['owner_id', 'status'], unique=False)
    op.alter_column('projects', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'ARCHIVED', name='project_status_enum'),
               existing_nullable=False)
    op.alter_column('projects', 'slug',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=220),
               existing_nullable=False)
    op.alter_column('projects', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.add_column('project_members', sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint('uq_project_member', 'project_members', type_='unique')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_id'), table_name='project_members')
    op.drop_column('project_members', 'updated_at')
    op.drop_column('project_members', 'created_at')
    op.drop_column('project_members', 'id')
    # ### end Alembic commands ###
